workflows:
  ios-build:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build app
        script: |
          xcodebuild \
            -project "Example/PaymentSheet Example/PaymentSheet Example.xcodeproj" \
            -scheme "PaymentSheet Example" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            clean build

